---
stages:
- test

.poetry:
  image: python:3.10-slim
  before_script:
    - pip install poetry
    - poetry config http-basic.artifactory-tdp ${ARTIFACTORY_USER} ${ARTIFACTORY_PASS}
    - apt update && apt install -y libmariadb-dev gcc


linting:
  stage: test
  extends: .poetry
  script:
    - poetry install
    - poetry run pyright src tests
    - poetry run flake8 src tests
    - poetry run black --check src tests
    - poetry run isort -c src tests

tests:
  stage: test
  extends: .poetry
  services:
    - name: mariadb:latest
      variables:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: smartlink
        MYSQL_USER: smartlink
        MYSQL_PASSWORD: smartlink
      alias: mariadb
  before_script:
    - !reference [.poetry, before_script]
    - apt update && apt install -y mariadb-client
  script:
    - mariadb -h mariadb -u smartlink --password=smartlink smartlink < tests/smartlink.sql
    - poetry install
    - poetry run pytest tests
