version: "3"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=smartlink
      - MYSQL_USER=smartlink
      - MYSQL_PASSWORD=smartlink
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9090:80

volumes:
  db:
